import styles from './Logando/login.module.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function LogandoLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.body}>{children}</body>
    </html>
  )
}
