import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import  styles from './globals.module.css';
import { UserProviderFromProviders } from '@/providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body 
      className= {styles.body}
      >
        <UserProviderFromProviders>
        {children}

        </UserProviderFromProviders>
      
      </body>
    </html>
  )
}
